// <auto-generated />
using System;
using Calametra.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Calametra.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260916103307_AddLguSourceNameOverride")]
    partial class AddLguSourceNameOverride
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Calametra.Application.Abstractions.Data.ConfirmedLguLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalPsgcCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_psgc_code");

                    b.Property<Guid>("ConfirmedAgainstEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_against_edition_id");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evidence");

                    b.Property<string>("HistoricalPsgcCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("historical_psgc_code");

                    b.Property<Guid>("LguId")
                        .HasColumnType("uuid")
                        .HasColumnName("lgu_id");

                    b.Property<string>("LguLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lgu_level");

                    b.Property<string>("LguName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lgu_name");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.HasKey("Id")
                        .HasName("pk_confirmed_lgu_links");

                    b.ToTable((string)null);

                    b.ToView("lgu_code_links_confirmed", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Administrative.Lgu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalPsgcCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("canonical_psgc_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParentCanonicalPsgcCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_canonical_psgc_code");

                    b.Property<Guid>("RegisterEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("register_edition_id");

                    b.Property<string>("RegisterStatedHistoricalCode")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("register_stated_historical_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lgus");

                    b.HasIndex("CanonicalPsgcCode")
                        .IsUnique()
                        .HasDatabaseName("ix_lgus_canonical_psgc_code");

                    b.HasIndex("ParentCanonicalPsgcCode")
                        .HasDatabaseName("ix_lgus_parent_canonical_psgc_code");

                    b.ToTable("lgus", null, t =>
                        {
                            t.HasCheckConstraint("ck_lgus_canonical_code_is_ten_digits", "char_length(canonical_psgc_code) = 10 AND canonical_psgc_code ~ '^[0-9]+$'");
                        });
                });

            modelBuilder.Entity("Calametra.Domain.Administrative.LguBoundary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AreaSquareKm")
                        .HasColumnType("double precision")
                        .HasColumnName("area_square_km");

                    b.Property<string>("CanonicalPsgcCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("canonical_psgc_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExtractId")
                        .HasColumnType("uuid")
                        .HasColumnName("extract_id");

                    b.Property<string>("ExtractVersion")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("extract_version");

                    b.Property<DateTimeOffset>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<MultiPolygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geography (MultiPolygon, 4326)")
                        .HasColumnName("geometry");

                    b.Property<Guid>("LguId")
                        .HasColumnType("uuid")
                        .HasColumnName("lgu_id");

                    b.Property<int>("OsmAdminLevel")
                        .HasColumnType("integer")
                        .HasColumnName("osm_admin_level");

                    b.Property<string>("OsmName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("osm_name");

                    b.Property<string>("OsmRefTag")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("osm_ref_tag");

                    b.Property<long?>("OsmRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("osm_relation_id");

                    b.Property<string>("RepairNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("repair_note");

                    b.Property<string>("SourceFeatureCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_feature_code");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid?>("SupersededByBoundaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_boundary_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<bool>("WasRepaired")
                        .HasColumnType("boolean")
                        .HasColumnName("was_repaired");

                    b.HasKey("Id")
                        .HasName("pk_lgu_boundaries");

                    b.HasIndex("ExtractId")
                        .HasDatabaseName("ix_lgu_boundaries_extract_id");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_lgu_boundaries_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("LguId")
                        .IsUnique()
                        .HasDatabaseName("ux_lgu_boundaries_in_force_per_lgu")
                        .HasFilter("valid_to IS NULL");

                    b.HasIndex("OsmRelationId")
                        .HasDatabaseName("ix_lgu_boundaries_osm_relation_id");

                    b.HasIndex("SourceFeatureCode")
                        .HasDatabaseName("ix_lgu_boundaries_source_feature_code");

                    b.ToTable("lgu_boundaries", null, t =>
                        {
                            t.HasCheckConstraint("ck_lgu_boundaries_area_is_positive", "area_square_km > 0");

                            t.HasCheckConstraint("ck_lgu_boundaries_repair_is_explained", "NOT was_repaired OR repair_note IS NOT NULL");

                            t.HasCheckConstraint("ck_lgu_boundaries_supersession_is_complete", "(valid_to IS NULL AND superseded_by_boundary_id IS NULL) OR (valid_to IS NOT NULL AND superseded_by_boundary_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_lgu_boundaries_valid_period_is_ordered", "valid_to IS NULL OR valid_to >= valid_from");
                        });
                });

            modelBuilder.Entity("Calametra.Domain.Administrative.LguBoundaryExtract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessRoute")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("access_route");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at");

                    b.Property<string>("AcquisitionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("acquisition_note");

                    b.Property<int>("BoundariesRead")
                        .HasColumnType("integer")
                        .HasColumnName("boundaries_read");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("file_sha256")
                        .IsFixedLength();

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("label");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provenance");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("Vintage")
                        .HasColumnType("date")
                        .HasColumnName("vintage");

                    b.HasKey("Id")
                        .HasName("pk_lgu_boundary_extracts");

                    b.HasIndex("FileSha256")
                        .IsUnique()
                        .HasDatabaseName("ux_lgu_boundary_extracts_per_file")
                        .HasFilter("file_sha256 IS NOT NULL");

                    b.HasIndex("Label", "AccessRoute")
                        .HasDatabaseName("ix_lgu_boundary_extracts_label_access_route");

                    b.ToTable("lgu_boundary_extracts", null, t =>
                        {
                            t.HasCheckConstraint("ck_lgu_boundary_extracts_file_details_are_paired", "(original_file_name IS NULL AND file_sha256 IS NULL) OR (original_file_name IS NOT NULL AND file_sha256 IS NOT NULL)");

                            t.HasCheckConstraint("ck_lgu_boundary_extracts_hash_is_hex", "file_sha256 IS NULL OR file_sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("Calametra.Domain.Administrative.LguCodeLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConfirmedAgainstEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_against_edition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("evidence");

                    b.Property<string>("HistoricalPsgcCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("historical_psgc_code");

                    b.Property<Guid>("LguId")
                        .HasColumnType("uuid")
                        .HasColumnName("lgu_id");

                    b.Property<bool>("NamesAgree")
                        .HasColumnType("boolean")
                        .HasColumnName("names_agree");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("ProposalBasis")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("proposal_basis");

                    b.Property<Guid>("ProposedAgainstEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposed_against_edition_id");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposed_at");

                    b.Property<string>("ProposedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("proposed_by");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lgu_code_links");

                    b.HasIndex("HistoricalPsgcCode")
                        .HasDatabaseName("ix_lgu_code_links_historical_psgc_code");

                    b.HasIndex("LguId")
                        .IsUnique()
                        .HasDatabaseName("ux_lgu_code_links_confirmed_per_lgu")
                        .HasFilter("status = 'Confirmed'");

                    b.HasIndex("PlaceId")
                        .IsUnique()
                        .HasDatabaseName("ux_lgu_code_links_confirmed_per_place")
                        .HasFilter("status = 'Confirmed' AND place_id IS NOT NULL");

                    b.HasIndex("ProposedAgainstEditionId")
                        .HasDatabaseName("ix_lgu_code_links_proposed_against_edition_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_lgu_code_links_status");

                    b.HasIndex("LguId", "HistoricalPsgcCode")
                        .IsUnique()
                        .HasDatabaseName("ux_lgu_code_links_live_per_unit_and_code")
                        .HasFilter("status <> 'Superseded'");

                    b.ToTable("lgu_code_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_lgu_code_links_confirmed_is_complete", "status <> 'Confirmed' OR (\r\n    evidence <> 'Unknown'\r\n    AND reviewed_by IS NOT NULL\r\n    AND reviewed_at IS NOT NULL\r\n    AND confirmed_against_edition_id IS NOT NULL\r\n    AND (evidence <> 'ManualReview' OR reason IS NOT NULL)\r\n    AND (evidence <> 'DigitReslice' OR names_agree)\r\n)");

                            t.HasCheckConstraint("ck_lgu_code_links_historical_code_is_nine_digits", "char_length(historical_psgc_code) = 9 AND historical_psgc_code ~ '^[0-9]+$'");

                            t.HasCheckConstraint("ck_lgu_code_links_rejected_has_reason", "status <> 'Rejected' OR (reviewed_by IS NOT NULL AND reason IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Calametra.Domain.Administrative.LguCrosswalkException", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("AcceptedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("accepted_by");

                    b.Property<string>("CanonicalPsgcCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("canonical_psgc_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DirectoryPsgcCode")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("directory_psgc_code");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("LguId")
                        .HasColumnType("uuid")
                        .HasColumnName("lgu_id");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RegisterEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("register_edition_id");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lgu_crosswalk_exceptions");

                    b.HasIndex("RegisterEditionId")
                        .HasDatabaseName("ix_lgu_crosswalk_exceptions_register_edition_id");

                    b.HasIndex("LguId", "RegisterEditionId")
                        .IsUnique()
                        .HasDatabaseName("ux_lgu_crosswalk_exceptions_per_unit_and_edition")
                        .HasFilter("lgu_id IS NOT NULL");

                    b.HasIndex("PlaceId", "RegisterEditionId")
                        .IsUnique()
                        .HasDatabaseName("ux_lgu_crosswalk_exceptions_per_place_and_edition")
                        .HasFilter("place_id IS NOT NULL");

                    b.ToTable("lgu_crosswalk_exceptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_lgu_crosswalk_exceptions_has_one_subject", "(kind = 'RegisterUnitHasNoHistoricalCode'\r\n    AND lgu_id IS NOT NULL AND canonical_psgc_code IS NOT NULL AND place_id IS NULL)\r\nOR (kind = 'DirectoryRowHasNoRegisterUnit'\r\n    AND place_id IS NOT NULL AND directory_psgc_code IS NOT NULL AND lgu_id IS NULL)");

                            t.HasCheckConstraint("ck_lgu_crosswalk_exceptions_reason_is_written", "char_length(btrim(reason)) >= 20");
                        });
                });

            modelBuilder.Entity("Calametra.Domain.Administrative.LguEditionCorrespondence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConfirmedAgainstEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_against_edition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentCanonicalPsgcCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("current_canonical_psgc_code")
                        .IsFixedLength();

                    b.Property<Guid>("CurrentLguId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_lgu_id");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("evidence");

                    b.Property<bool>("HasRegisterBridge")
                        .HasColumnType("boolean")
                        .HasColumnName("has_register_bridge");

                    b.Property<string>("LegacyCanonicalPsgcCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("legacy_canonical_psgc_code")
                        .IsFixedLength();

                    b.Property<string>("LegacyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legacy_name");

                    b.Property<bool>("NamesAgree")
                        .HasColumnType("boolean")
                        .HasColumnName("names_agree");

                    b.Property<string>("ProposalBasis")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("proposal_basis");

                    b.Property<Guid>("ProposedAgainstEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposed_against_edition_id");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposed_at");

                    b.Property<string>("ProposedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("proposed_by");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lgu_edition_correspondences");

                    b.HasIndex("CurrentLguId")
                        .IsUnique()
                        .HasDatabaseName("ux_lgu_edition_correspondences_confirmed_per_unit")
                        .HasFilter("status = 'Confirmed'");

                    b.HasIndex("LegacyCanonicalPsgcCode")
                        .IsUnique()
                        .HasDatabaseName("ux_lgu_edition_correspondences_live_per_legacy_code")
                        .HasFilter("status <> 'Superseded'");

                    b.HasIndex("ProposedAgainstEditionId")
                        .HasDatabaseName("ix_lgu_edition_correspondences_proposed_against_edition_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_lgu_edition_correspondences_status");

                    b.ToTable("lgu_edition_correspondences", null, t =>
                        {
                            t.HasCheckConstraint("ck_lgu_edition_correspondences_codes_are_ten_digits", "legacy_canonical_psgc_code ~ '^[0-9]{10}$' AND current_canonical_psgc_code ~ '^[0-9]{10}$'");

                            t.HasCheckConstraint("ck_lgu_edition_correspondences_codes_differ", "legacy_canonical_psgc_code <> current_canonical_psgc_code");

                            t.HasCheckConstraint("ck_lgu_edition_correspondences_confirmed_is_complete", "status <> 'Confirmed' OR (\r\n    reviewed_by IS NOT NULL\r\n    AND reviewed_at IS NOT NULL\r\n    AND confirmed_against_edition_id IS NOT NULL\r\n    AND evidence IN ('EditionCorrespondence', 'ManualReview')\r\n    AND (evidence <> 'ManualReview' OR char_length(btrim(reason)) >= 20)\r\n    AND (evidence <> 'EditionCorrespondence' OR names_agree)\r\n)");

                            t.HasCheckConstraint("ck_lgu_edition_correspondences_rejected_has_reason", "status <> 'Rejected' OR (reviewed_by IS NOT NULL AND reason IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Calametra.Domain.Administrative.LguSourceNameOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalPsgcCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("canonical_psgc_code")
                        .IsFixedLength();

                    b.Property<Guid>("ConfirmedAgainstEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_against_edition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("RegisterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("register_name");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lgu_source_name_overrides");

                    b.HasIndex("CanonicalPsgcCode", "SourceName")
                        .IsUnique()
                        .HasDatabaseName("ux_lgu_source_name_overrides_per_code_and_name");

                    b.ToTable("lgu_source_name_overrides", null, t =>
                        {
                            t.HasCheckConstraint("ck_lgu_source_name_overrides_code_is_ten_digits", "canonical_psgc_code ~ '^[0-9]{10}$'");

                            t.HasCheckConstraint("ck_lgu_source_name_overrides_reason_is_evidenced", "char_length(btrim(reason)) >= 40");
                        });
                });

            modelBuilder.Entity("Calametra.Domain.Administrative.PsgcRegisterEdition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessRoute")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("access_route");

                    b.Property<string>("AcquisitionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("acquisition_note");

                    b.Property<int>("CityCount")
                        .HasColumnType("integer")
                        .HasColumnName("city_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("FileSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("file_sha256")
                        .IsFixedLength();

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("MunicipalityCount")
                        .HasColumnType("integer")
                        .HasColumnName("municipality_count");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provenance");

                    b.Property<int>("ProvinceCount")
                        .HasColumnType("integer")
                        .HasColumnName("province_count");

                    b.Property<DateOnly?>("PublicationDate")
                        .HasColumnType("date")
                        .HasColumnName("publication_date");

                    b.Property<int>("RegionCount")
                        .HasColumnType("integer")
                        .HasColumnName("region_count");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.Property<Guid?>("SupersededByEditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_edition_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("UpstreamLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upstream_last_modified");

                    b.HasKey("Id")
                        .HasName("pk_psgc_register_editions");

                    b.HasIndex("FileSha256")
                        .HasDatabaseName("ix_psgc_register_editions_file_sha256");

                    b.HasIndex("SupersededAt")
                        .HasDatabaseName("ix_psgc_register_editions_superseded_at");

                    b.HasIndex("Label", "AccessRoute")
                        .IsUnique()
                        .HasDatabaseName("ix_psgc_register_editions_label_access_route");

                    b.ToTable("psgc_register_editions", null, t =>
                        {
                            t.HasCheckConstraint("ck_psgc_register_editions_hash_is_hex", "file_sha256 IS NULL OR file_sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("Calametra.Domain.Events.CycloneTrackPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("Classification")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<double?>("DistanceToLandKm")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_to_land_km");

                    b.Property<string>("ExternalStormId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_storm_id");

                    b.Property<int?>("GaleRadiusBearingDegrees")
                        .HasColumnType("integer")
                        .HasColumnName("gale_radius_bearing_degrees");

                    b.Property<double?>("GaleRadiusLongAxisNm")
                        .HasColumnType("double precision")
                        .HasColumnName("gale_radius_long_axis_nm");

                    b.Property<double?>("GaleRadiusNorthEastNm")
                        .HasColumnType("double precision")
                        .HasColumnName("gale_radius_north_east_nm");

                    b.Property<double?>("GaleRadiusNorthWestNm")
                        .HasColumnType("double precision")
                        .HasColumnName("gale_radius_north_west_nm");

                    b.Property<double?>("GaleRadiusShortAxisNm")
                        .HasColumnType("double precision")
                        .HasColumnName("gale_radius_short_axis_nm");

                    b.Property<double?>("GaleRadiusSouthEastNm")
                        .HasColumnType("double precision")
                        .HasColumnName("gale_radius_south_east_nm");

                    b.Property<double?>("GaleRadiusSouthWestNm")
                        .HasColumnType("double precision")
                        .HasColumnName("gale_radius_south_west_nm");

                    b.Property<int>("GaleThresholdKnots")
                        .HasColumnType("integer")
                        .HasColumnName("gale_threshold_knots");

                    b.Property<Guid>("HazardEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("hazard_event_id");

                    b.Property<double?>("HurricaneRadiusNorthEastNm")
                        .HasColumnType("double precision")
                        .HasColumnName("hurricane_radius_north_east_nm");

                    b.Property<double?>("HurricaneRadiusNorthWestNm")
                        .HasColumnType("double precision")
                        .HasColumnName("hurricane_radius_north_west_nm");

                    b.Property<double?>("HurricaneRadiusSouthEastNm")
                        .HasColumnType("double precision")
                        .HasColumnName("hurricane_radius_south_east_nm");

                    b.Property<double?>("HurricaneRadiusSouthWestNm")
                        .HasColumnType("double precision")
                        .HasColumnName("hurricane_radius_south_west_nm");

                    b.Property<bool>("IsLandfall")
                        .HasColumnType("boolean")
                        .HasColumnName("is_landfall");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int?>("MinimumPressureMillibars")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_pressure_millibars");

                    b.Property<Point>("Position")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("position");

                    b.Property<double?>("RadiusOfMaximumWindNm")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_of_maximum_wind_nm");

                    b.Property<double?>("RadiusOutermostIsobarNm")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_outermost_isobar_nm");

                    b.Property<double?>("StormRadiusNorthEastNm")
                        .HasColumnType("double precision")
                        .HasColumnName("storm_radius_north_east_nm");

                    b.Property<double?>("StormRadiusNorthWestNm")
                        .HasColumnType("double precision")
                        .HasColumnName("storm_radius_north_west_nm");

                    b.Property<double?>("StormRadiusSouthEastNm")
                        .HasColumnType("double precision")
                        .HasColumnName("storm_radius_south_east_nm");

                    b.Property<double?>("StormRadiusSouthWestNm")
                        .HasColumnType("double precision")
                        .HasColumnName("storm_radius_south_west_nm");

                    b.Property<string>("WindAveragingPeriod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("wind_averaging_period");

                    b.Property<string>("WindFieldGeometry")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("wind_field_geometry");

                    b.Property<double?>("WindSpeedKnots")
                        .HasColumnType("double precision")
                        .HasColumnName("wind_speed_knots");

                    b.HasKey("Id")
                        .HasName("pk_cyclone_track_points");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_cyclone_track_points_data_source_id");

                    b.HasIndex("ExternalStormId")
                        .HasDatabaseName("ix_cyclone_track_points_external_storm_id");

                    b.HasIndex("Position")
                        .HasDatabaseName("ix_cyclone_track_points_position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "gist");

                    b.HasIndex("HazardEventId", "CapturedAt")
                        .HasDatabaseName("ix_cyclone_track_points_hazard_event_id_captured_at");

                    b.HasIndex("WindAveragingPeriod", "WindSpeedKnots")
                        .HasDatabaseName("ix_cyclone_track_points_wind_averaging_period_wind_speed_knots");

                    b.HasIndex("HazardEventId", "DataSourceId", "CapturedAt")
                        .IsUnique()
                        .HasDatabaseName("ix_cyclone_track_points_hazard_event_id_data_source_id_capture");

                    b.ToTable("cyclone_track_points", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Events.EarthquakeObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<double?>("DepthKilometres")
                        .HasColumnType("double precision")
                        .HasColumnName("depth_kilometres");

                    b.Property<string>("DepthQuality")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("depth_quality");

                    b.Property<Point>("Epicenter")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("epicenter");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_event_id");

                    b.Property<Guid>("HazardEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("hazard_event_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MagnitudeScale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("magnitude_scale");

                    b.Property<double?>("MagnitudeValue")
                        .HasColumnType("double precision")
                        .HasColumnName("magnitude_value");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_earthquake_observations");

                    b.HasIndex("Epicenter")
                        .HasDatabaseName("ix_earthquake_observations_epicenter");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Epicenter"), "gist");

                    b.HasIndex("DataSourceId", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_earthquake_observations_data_source_id_external_event_id");

                    b.HasIndex("DepthQuality", "DepthKilometres")
                        .HasDatabaseName("ix_earthquake_observations_depth_quality_depth_kilometres");

                    b.HasIndex("HazardEventId", "DataSourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_earthquake_observations_hazard_event_id_data_source_id");

                    b.HasIndex("MagnitudeValue", "MagnitudeScale")
                        .HasDatabaseName("ix_earthquake_observations_magnitude_value_magnitude_scale");

                    b.ToTable("earthquake_observations", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Events.HazardEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Point>("CanonicalEpicenter")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("canonical_epicenter");

                    b.Property<DateTimeOffset>("CanonicalOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canonical_occurred_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LocalName")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("local_name");

                    b.Property<string>("Name")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PreferredObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_observation_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hazard_events");

                    b.HasIndex("CanonicalEpicenter")
                        .HasDatabaseName("ix_hazard_events_canonical_epicenter");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CanonicalEpicenter"), "gist");

                    b.HasIndex("Type", "CanonicalOccurredAt")
                        .HasDatabaseName("ix_hazard_events_type_canonical_occurred_at");

                    b.HasIndex("Type", "Name")
                        .HasDatabaseName("ix_hazard_events_type_name");

                    b.ToTable("hazard_events", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Hazards.HazardFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes_json");

                    b.Property<string>("Classification")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geography (Geometry, 4326)")
                        .HasColumnName("geometry");

                    b.Property<Guid>("HazardLayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("hazard_layer_id");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hazard_features");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_hazard_features_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("HazardLayerId")
                        .HasDatabaseName("ix_hazard_features_hazard_layer_id");

                    b.HasIndex("DataSourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_hazard_features_data_source_id_external_id");

                    b.ToTable("hazard_features", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Hazards.HazardLayerDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CachedTileEndpoint")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cached_tile_endpoint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("DeliveryMode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("delivery_mode");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Explainer")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explainer");

                    b.Property<string>("FeatureInfoEndpoint")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("feature_info_endpoint");

                    b.Property<string>("HazardType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("hazard_type");

                    b.Property<string>("InterpretationNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("interpretation_note");

                    b.Property<bool>("IsEnabledByDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled_by_default");

                    b.Property<string>("Lens")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("lens");

                    b.Property<int?>("MinimumZoom")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_zoom");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<bool>("SupportsFeatureInfo")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_feature_info");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WmsEndpoint")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("wms_endpoint");

                    b.Property<string>("WmsLayerName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("wms_layer_name");

                    b.HasKey("Id")
                        .HasName("pk_hazard_layers");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_hazard_layers_data_source_id");

                    b.HasIndex("Lens", "SortOrder")
                        .HasDatabaseName("ix_hazard_layers_lens_sort_order");

                    b.ToTable("hazard_layers", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Places.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<MultiPolygon>("Boundary")
                        .HasColumnType("geography (MultiPolygon, 4326)")
                        .HasColumnName("boundary");

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("centroid");

                    b.Property<Guid?>("CoordinateDataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("coordinate_data_source_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_place_id");

                    b.Property<DateTimeOffset?>("PopulationAsOf")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("population_as_of");

                    b.Property<Guid?>("PopulationDataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("population_data_source_id");

                    b.Property<long?>("PopulationEstimate")
                        .HasColumnType("bigint")
                        .HasColumnName("population_estimate");

                    b.Property<string>("PsgcCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("psgc_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("ix_places_boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("Centroid")
                        .HasDatabaseName("ix_places_centroid");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "gist");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_places_data_source_id");

                    b.HasIndex("ParentPlaceId")
                        .HasDatabaseName("ix_places_parent_place_id");

                    b.HasIndex("PsgcCode")
                        .IsUnique()
                        .HasDatabaseName("ix_places_psgc_code")
                        .HasFilter("psgc_code IS NOT NULL");

                    b.HasIndex("Kind", "Name")
                        .HasDatabaseName("ix_places_kind_name");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Sources.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("access_kind");

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agency");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("attribution");

                    b.Property<string>("CoverageNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("coverage_notes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatasetName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("dataset_name");

                    b.Property<bool>("IsAuthoritativeForPhilippines")
                        .HasColumnType("boolean")
                        .HasColumnName("is_authoritative_for_philippines");

                    b.Property<bool>("IsRedistributable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_redistributable");

                    b.Property<string>("LastPayloadChecksum")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_payload_checksum");

                    b.Property<DateTimeOffset?>("LastRetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retrieved_at");

                    b.Property<double?>("MinimumReliableMagnitude")
                        .HasColumnType("double precision")
                        .HasColumnName("minimum_reliable_magnitude");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_url");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_version");

                    b.Property<string>("TermsUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("terms_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_data_sources");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_data_sources_slug");

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Events.CycloneTrackPoint", b =>
                {
                    b.HasOne("Calametra.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cyclone_track_points_data_sources_data_source_id");

                    b.HasOne("Calametra.Domain.Events.HazardEvent", null)
                        .WithMany("TrackPoints")
                        .HasForeignKey("HazardEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cyclone_track_points_hazard_events_hazard_event_id");
                });

            modelBuilder.Entity("Calametra.Domain.Events.EarthquakeObservation", b =>
                {
                    b.HasOne("Calametra.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_earthquake_observations_data_sources_data_source_id");

                    b.HasOne("Calametra.Domain.Events.HazardEvent", null)
                        .WithMany("Observations")
                        .HasForeignKey("HazardEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_earthquake_observations_hazard_events_hazard_event_id");
                });

            modelBuilder.Entity("Calametra.Domain.Hazards.HazardFeature", b =>
                {
                    b.HasOne("Calametra.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hazard_features_data_sources_data_source_id");

                    b.HasOne("Calametra.Domain.Hazards.HazardLayerDefinition", null)
                        .WithMany()
                        .HasForeignKey("HazardLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hazard_features_hazard_layers_hazard_layer_id");
                });

            modelBuilder.Entity("Calametra.Domain.Hazards.HazardLayerDefinition", b =>
                {
                    b.HasOne("Calametra.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hazard_layers_data_sources_data_source_id");
                });

            modelBuilder.Entity("Calametra.Domain.Places.Place", b =>
                {
                    b.HasOne("Calametra.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_places_data_sources_data_source_id");

                    b.HasOne("Calametra.Domain.Places.Place", null)
                        .WithMany()
                        .HasForeignKey("ParentPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_places_places_parent_place_id");
                });

            modelBuilder.Entity("Calametra.Domain.Events.HazardEvent", b =>
                {
                    b.Navigation("Observations");

                    b.Navigation("TrackPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
