// <auto-generated />
using System;
using Calametra.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Calametra.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Calametra.Domain.Events.EventObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<double?>("DepthKilometres")
                        .HasColumnType("double precision")
                        .HasColumnName("depth_kilometres");

                    b.Property<string>("DepthQuality")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("depth_quality");

                    b.Property<Point>("Epicenter")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("epicenter");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_event_id");

                    b.Property<Guid>("HazardEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("hazard_event_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MagnitudeScale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("magnitude_scale");

                    b.Property<double?>("MagnitudeValue")
                        .HasColumnType("double precision")
                        .HasColumnName("magnitude_value");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_event_observations");

                    b.HasIndex("Epicenter")
                        .HasDatabaseName("ix_event_observations_epicenter");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Epicenter"), "gist");

                    b.HasIndex("DataSourceId", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_observations_data_source_id_external_event_id");

                    b.HasIndex("DepthQuality", "DepthKilometres")
                        .HasDatabaseName("ix_event_observations_depth_quality_depth_kilometres");

                    b.HasIndex("HazardEventId", "DataSourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_observations_hazard_event_id_data_source_id");

                    b.HasIndex("MagnitudeValue", "MagnitudeScale")
                        .HasDatabaseName("ix_event_observations_magnitude_value_magnitude_scale");

                    b.ToTable("event_observations", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Events.EventTrackPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("Classification")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<double?>("DistanceToLandKm")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_to_land_km");

                    b.Property<Guid>("HazardEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("hazard_event_id");

                    b.Property<bool>("IsLandfall")
                        .HasColumnType("boolean")
                        .HasColumnName("is_landfall");

                    b.Property<int?>("MaxSustainedWindKnots")
                        .HasColumnType("integer")
                        .HasColumnName("max_sustained_wind_knots");

                    b.Property<int?>("MinimumPressureMillibars")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_pressure_millibars");

                    b.Property<Point>("Position")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_event_track_points");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_event_track_points_data_source_id");

                    b.HasIndex("Position")
                        .HasDatabaseName("ix_event_track_points_position");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Position"), "gist");

                    b.HasIndex("HazardEventId", "CapturedAt")
                        .HasDatabaseName("ix_event_track_points_hazard_event_id_captured_at");

                    b.ToTable("event_track_points", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Events.HazardEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Point>("CanonicalEpicenter")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("canonical_epicenter");

                    b.Property<DateTimeOffset>("CanonicalOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canonical_occurred_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PreferredObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_observation_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hazard_events");

                    b.HasIndex("CanonicalEpicenter")
                        .HasDatabaseName("ix_hazard_events_canonical_epicenter");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CanonicalEpicenter"), "gist");

                    b.HasIndex("Type", "CanonicalOccurredAt")
                        .HasDatabaseName("ix_hazard_events_type_canonical_occurred_at");

                    b.ToTable("hazard_events", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Hazards.HazardFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttributesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes_json");

                    b.Property<string>("Classification")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geography (Geometry, 4326)")
                        .HasColumnName("geometry");

                    b.Property<Guid>("HazardLayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("hazard_layer_id");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_hazard_features");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_hazard_features_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("HazardLayerId")
                        .HasDatabaseName("ix_hazard_features_hazard_layer_id");

                    b.HasIndex("DataSourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_hazard_features_data_source_id_external_id");

                    b.ToTable("hazard_features", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Hazards.HazardLayerDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<string>("DeliveryMode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("delivery_mode");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Explainer")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explainer");

                    b.Property<string>("FeatureInfoEndpoint")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("feature_info_endpoint");

                    b.Property<string>("HazardType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("hazard_type");

                    b.Property<string>("InterpretationNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("interpretation_note");

                    b.Property<bool>("IsEnabledByDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled_by_default");

                    b.Property<string>("Lens")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("lens");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<bool>("SupportsFeatureInfo")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_feature_info");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WmsEndpoint")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("wms_endpoint");

                    b.Property<string>("WmsLayerName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("wms_layer_name");

                    b.HasKey("Id")
                        .HasName("pk_hazard_layers");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_hazard_layers_data_source_id");

                    b.HasIndex("Lens", "SortOrder")
                        .HasDatabaseName("ix_hazard_layers_lens_sort_order");

                    b.ToTable("hazard_layers", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Places.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<MultiPolygon>("Boundary")
                        .HasColumnType("geography (MultiPolygon, 4326)")
                        .HasColumnName("boundary");

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("centroid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_place_id");

                    b.Property<DateTimeOffset?>("PopulationAsOf")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("population_as_of");

                    b.Property<Guid?>("PopulationDataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("population_data_source_id");

                    b.Property<long?>("PopulationEstimate")
                        .HasColumnType("bigint")
                        .HasColumnName("population_estimate");

                    b.Property<string>("PsgcCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("psgc_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("ix_places_boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("Centroid")
                        .HasDatabaseName("ix_places_centroid");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "gist");

                    b.HasIndex("ParentPlaceId")
                        .HasDatabaseName("ix_places_parent_place_id");

                    b.HasIndex("PsgcCode")
                        .IsUnique()
                        .HasDatabaseName("ix_places_psgc_code")
                        .HasFilter("psgc_code IS NOT NULL");

                    b.HasIndex("Kind", "Name")
                        .HasDatabaseName("ix_places_kind_name");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Sources.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("access_kind");

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agency");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("attribution");

                    b.Property<string>("CoverageNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("coverage_notes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatasetName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("dataset_name");

                    b.Property<bool>("IsAuthoritativeForPhilippines")
                        .HasColumnType("boolean")
                        .HasColumnName("is_authoritative_for_philippines");

                    b.Property<bool>("IsRedistributable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_redistributable");

                    b.Property<string>("LastPayloadChecksum")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_payload_checksum");

                    b.Property<DateTimeOffset?>("LastRetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_retrieved_at");

                    b.Property<double?>("MinimumReliableMagnitude")
                        .HasColumnType("double precision")
                        .HasColumnName("minimum_reliable_magnitude");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_url");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_version");

                    b.Property<string>("TermsUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("terms_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_data_sources");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_data_sources_slug");

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("Calametra.Domain.Events.EventObservation", b =>
                {
                    b.HasOne("Calametra.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_observations_data_sources_data_source_id");

                    b.HasOne("Calametra.Domain.Events.HazardEvent", null)
                        .WithMany("Observations")
                        .HasForeignKey("HazardEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_observations_hazard_events_hazard_event_id");
                });

            modelBuilder.Entity("Calametra.Domain.Events.EventTrackPoint", b =>
                {
                    b.HasOne("Calametra.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_track_points_data_sources_data_source_id");

                    b.HasOne("Calametra.Domain.Events.HazardEvent", null)
                        .WithMany("TrackPoints")
                        .HasForeignKey("HazardEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_track_points_hazard_events_hazard_event_id");
                });

            modelBuilder.Entity("Calametra.Domain.Hazards.HazardFeature", b =>
                {
                    b.HasOne("Calametra.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hazard_features_data_sources_data_source_id");

                    b.HasOne("Calametra.Domain.Hazards.HazardLayerDefinition", null)
                        .WithMany()
                        .HasForeignKey("HazardLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hazard_features_hazard_layers_hazard_layer_id");
                });

            modelBuilder.Entity("Calametra.Domain.Hazards.HazardLayerDefinition", b =>
                {
                    b.HasOne("Calametra.Domain.Sources.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hazard_layers_data_sources_data_source_id");
                });

            modelBuilder.Entity("Calametra.Domain.Places.Place", b =>
                {
                    b.HasOne("Calametra.Domain.Places.Place", null)
                        .WithMany()
                        .HasForeignKey("ParentPlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_places_places_parent_place_id");
                });

            modelBuilder.Entity("Calametra.Domain.Events.HazardEvent", b =>
                {
                    b.Navigation("Observations");

                    b.Navigation("TrackPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
